package T2.ScannerTests;
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int E_SIMB_NOT_FOUND = 55;
  public static final int OP_MAYOR = 33;
  public static final int LIT_INT = 51;
  public static final int L_CORCHETE = 45;
  public static final int LIT_FLOAT = 52;
  public static final int DOS_PUNTOS = 50;
  public static final int OP_NOT = 39;
  public static final int OP_AND = 37;
  public static final int CONTINUE = 9;
  public static final int INT = 12;
  public static final int OP_ASIGN = 40;
  public static final int FOR = 6;
  public static final int OP_DIV = 28;
  public static final int L_LLAVE = 43;
  public static final int MEDIAN = 22;
  public static final int IDENTIFICADOR = 24;
  public static final int R_LLAVE = 44;
  public static final int FN = 10;
  public static final int R_CORCHETE = 46;
  public static final int BOOL = 11;
  public static final int OP_DIFERENTE = 36;
  public static final int MIN = 21;
  public static final int IF = 2;
  public static final int PUNTO_COMA = 48;
  public static final int OP_MOD = 29;
  public static final int EOF = 0;
  public static final int RETURN = 7;
  public static final int TRUE = 15;
  public static final int error = 1;
  public static final int COMA = 47;
  public static final int MODE = 23;
  public static final int LIT_STRING = 53;
  public static final int OP_MULT = 27;
  public static final int OP_OR = 38;
  public static final int NULL = 17;
  public static final int OP_RESTA = 26;
  public static final int MEAN = 19;
  public static final int BREAK = 8;
  public static final int L_PARENTESIS = 41;
  public static final int OP_MAYOR_IGUAL = 34;
  public static final int ELSE = 3;
  public static final int PUNTO = 49;
  public static final int OP_IGUAL = 35;
  public static final int WHILE = 5;
  public static final int FLOAT = 13;
  public static final int OP_MENOR_IGUAL = 32;
  public static final int R_PARENTESIS = 42;
  public static final int STRING = 14;
  public static final int E_NUM_START_ZERO = 54;
  public static final int OP_SUMA = 25;
  public static final int FALSE = 16;
  public static final int MAX = 20;
  public static final int OP_POT = 30;
  public static final int ELIF = 4;
  public static final int E_ID_START_DIGIT = 56;
  public static final int PRINT = 18;
  public static final int OP_MENOR = 31;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IF",
  "ELSE",
  "ELIF",
  "WHILE",
  "FOR",
  "RETURN",
  "BREAK",
  "CONTINUE",
  "FN",
  "BOOL",
  "INT",
  "FLOAT",
  "STRING",
  "TRUE",
  "FALSE",
  "NULL",
  "PRINT",
  "MEAN",
  "MAX",
  "MIN",
  "MEDIAN",
  "MODE",
  "IDENTIFICADOR",
  "OP_SUMA",
  "OP_RESTA",
  "OP_MULT",
  "OP_DIV",
  "OP_MOD",
  "OP_POT",
  "OP_MENOR",
  "OP_MENOR_IGUAL",
  "OP_MAYOR",
  "OP_MAYOR_IGUAL",
  "OP_IGUAL",
  "OP_DIFERENTE",
  "OP_AND",
  "OP_OR",
  "OP_NOT",
  "OP_ASIGN",
  "L_PARENTESIS",
  "R_PARENTESIS",
  "L_LLAVE",
  "R_LLAVE",
  "L_CORCHETE",
  "R_CORCHETE",
  "COMA",
  "PUNTO_COMA",
  "PUNTO",
  "DOS_PUNTOS",
  "LIT_INT",
  "LIT_FLOAT",
  "LIT_STRING",
  "E_NUM_START_ZERO",
  "E_SIMB_NOT_FOUND",
  "E_ID_START_DIGIT"
  };
}

