
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package model.parser;

/** CUP generated class containing symbol constants. */
public class ParserSym {
  /* terminals */
  public static final int GETASCII = 32;
  public static final int OP_MAYOR = 50;
  public static final int LIT_INT = 19;
  public static final int CHAR = 15;
  public static final int L_CORCHETE = 62;
  public static final int LIT_FLOAT = 20;
  public static final int DOS_PUNTOS = 67;
  public static final int OP_NOT = 56;
  public static final int OP_AND = 54;
  public static final int CONTINUE = 9;
  public static final int INT = 12;
  public static final int PRINTLN = 23;
  public static final int OP_ASIGN = 57;
  public static final int FLOOR = 36;
  public static final int FOR = 6;
  public static final int OP_DIV = 45;
  public static final int SORT = 34;
  public static final int L_LLAVE = 60;
  public static final int MEDIAN = 28;
  public static final int IDENTIFICADOR = 41;
  public static final int COPY = 35;
  public static final int R_LLAVE = 61;
  public static final int FN = 10;
  public static final int R_CORCHETE = 63;
  public static final int OP_DIFERENTE = 53;
  public static final int MIN = 27;
  public static final int IF = 2;
  public static final int PUNTO_COMA = 65;
  public static final int OP_MOD = 46;
  public static final int EOF = 0;
  public static final int BOOLEAN = 11;
  public static final int RETURN = 7;
  public static final int TRUE = 16;
  public static final int error = 1;
  public static final int COMA = 64;
  public static final int MODE = 29;
  public static final int OP_MULT = 44;
  public static final int LIT_STRING = 21;
  public static final int OP_OR = 55;
  public static final int NULL = 18;
  public static final int OP_RESTA = 43;
  public static final int LIT_CHAR = 22;
  public static final int MEAN = 25;
  public static final int BREAK = 8;
  public static final int L_PARENTESIS = 58;
  public static final int TOINT = 39;
  public static final int OP_MAYOR_IGUAL = 51;
  public static final int ELSE = 3;
  public static final int PUNTO = 66;
  public static final int OP_IGUAL = 52;
  public static final int TOFLOAT = 40;
  public static final int WHILE = 5;
  public static final int FLOAT = 13;
  public static final int OP_MENOR_IGUAL = 49;
  public static final int R_PARENTESIS = 59;
  public static final int LEN = 33;
  public static final int STRING = 14;
  public static final int OP_SUMA = 42;
  public static final int CEIL = 37;
  public static final int GETCHAR = 30;
  public static final int FALSE = 17;
  public static final int MAX = 26;
  public static final int OP_POT = 47;
  public static final int ELIF = 4;
  public static final int ROUND = 38;
  public static final int PRINT = 24;
  public static final int GETCHARFROMASCII = 31;
  public static final int OP_MENOR = 48;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IF",
  "ELSE",
  "ELIF",
  "WHILE",
  "FOR",
  "RETURN",
  "BREAK",
  "CONTINUE",
  "FN",
  "BOOLEAN",
  "INT",
  "FLOAT",
  "STRING",
  "CHAR",
  "TRUE",
  "FALSE",
  "NULL",
  "LIT_INT",
  "LIT_FLOAT",
  "LIT_STRING",
  "LIT_CHAR",
  "PRINTLN",
  "PRINT",
  "MEAN",
  "MAX",
  "MIN",
  "MEDIAN",
  "MODE",
  "GETCHAR",
  "GETCHARFROMASCII",
  "GETASCII",
  "LEN",
  "SORT",
  "COPY",
  "FLOOR",
  "CEIL",
  "ROUND",
  "TOINT",
  "TOFLOAT",
  "IDENTIFICADOR",
  "OP_SUMA",
  "OP_RESTA",
  "OP_MULT",
  "OP_DIV",
  "OP_MOD",
  "OP_POT",
  "OP_MENOR",
  "OP_MENOR_IGUAL",
  "OP_MAYOR",
  "OP_MAYOR_IGUAL",
  "OP_IGUAL",
  "OP_DIFERENTE",
  "OP_AND",
  "OP_OR",
  "OP_NOT",
  "OP_ASIGN",
  "L_PARENTESIS",
  "R_PARENTESIS",
  "L_LLAVE",
  "R_LLAVE",
  "L_CORCHETE",
  "R_CORCHETE",
  "COMA",
  "PUNTO_COMA",
  "PUNTO",
  "DOS_PUNTOS"
  };
}

