// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/data/Lexer.flex

package ScannerTests;
import model.scanner.Token;
import model.scanner.TokenType;

@SuppressWarnings("fallthrough")
class Lexer {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\1\1\4\22\0\1\1"+
    "\1\5\1\0\1\6\1\0\1\7\1\10\1\11\1\12"+
    "\1\13\1\14\1\15\1\16\1\17\1\20\1\21\1\22"+
    "\11\23\1\24\1\25\1\26\1\27\1\30\2\0\32\31"+
    "\1\32\1\0\1\33\1\34\1\31\1\0\1\35\1\36"+
    "\1\37\1\40\1\41\1\42\1\43\1\44\1\45\1\31"+
    "\1\46\1\47\1\50\1\51\1\52\1\53\1\31\1\54"+
    "\1\55\1\56\1\57\1\31\1\60\1\61\2\31\1\62"+
    "\1\63\1\64\7\0\1\3\73\0\1\31\7\0\1\31"+
    "\3\0\1\31\3\0\1\31\1\0\1\31\6\0\1\31"+
    "\1\0\1\31\4\0\1\31\7\0\1\31\3\0\1\31"+
    "\3\0\1\31\1\0\1\31\6\0\1\31\1\0\1\31"+
    "\u012b\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\3\1\2\1\4\2\1\1\5"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\2\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\14\23\1\27\1\1\1\30\1\31\1\32\1\0"+
    "\1\33\1\0\1\34\1\35\1\36\1\37\1\40\6\23"+
    "\1\41\1\23\1\42\13\23\1\43\1\44\7\23\1\45"+
    "\1\46\1\47\2\23\1\50\7\23\1\51\2\23\1\52"+
    "\1\53\2\23\1\54\1\23\1\55\1\56\3\23\1\57"+
    "\1\23\1\60\1\23\1\61\1\62\1\23\1\63\2\23"+
    "\1\64\1\23\1\65\1\66\1\33\1\23\1\67";

  private static int [] zzUnpackAction() {
    int [] result = new int[126];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\65\0\65\0\152\0\237\0\324\0\65\0\u0109"+
    "\0\u013e\0\65\0\65\0\65\0\65\0\65\0\65\0\65"+
    "\0\65\0\u0173\0\u01a8\0\65\0\65\0\u01dd\0\u0212\0\u0247"+
    "\0\u027c\0\65\0\65\0\65\0\u02b1\0\u02e6\0\u031b\0\u0350"+
    "\0\u0385\0\u03ba\0\u03ef\0\u0424\0\u0459\0\u048e\0\u04c3\0\u04f8"+
    "\0\65\0\u052d\0\65\0\65\0\65\0\u013e\0\u013e\0\u0562"+
    "\0\u0597\0\u05cc\0\65\0\65\0\65\0\u0601\0\u0636\0\u066b"+
    "\0\u06a0\0\u06d5\0\u070a\0\u027c\0\u073f\0\u027c\0\u0774\0\u07a9"+
    "\0\u07de\0\u0813\0\u0848\0\u087d\0\u08b2\0\u08e7\0\u091c\0\u0951"+
    "\0\u0986\0\65\0\u0562\0\u09bb\0\u09f0\0\u0a25\0\u0a5a\0\u0a8f"+
    "\0\u0ac4\0\u0af9\0\u027c\0\u027c\0\u027c\0\u0b2e\0\u0b63\0\u027c"+
    "\0\u0b98\0\u0bcd\0\u0c02\0\u0c37\0\u0c6c\0\u0ca1\0\u0cd6\0\u027c"+
    "\0\u0d0b\0\u0d40\0\u027c\0\u027c\0\u0d75\0\u0daa\0\u027c\0\u0ddf"+
    "\0\u027c\0\u027c\0\u0e14\0\u0e49\0\u0e7e\0\u027c\0\u0eb3\0\u027c"+
    "\0\u0ee8\0\u027c\0\u027c\0\u0f1d\0\u027c\0\u0f52\0\u0f87\0\u027c"+
    "\0\u0fbc\0\u027c\0\u027c\0\u027c\0\u0ff1\0\u027c";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[126];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\1\4\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\1\33\1\34\1\31\1\35\1\36\1\31"+
    "\1\37\1\40\2\31\1\41\2\31\1\42\1\43\1\31"+
    "\1\44\1\45\1\46\1\47\1\31\1\50\1\31\1\51"+
    "\1\52\1\53\67\0\1\3\111\0\1\54\35\0\2\6"+
    "\1\3\1\6\1\4\60\6\10\0\1\55\54\0\2\56"+
    "\1\0\1\56\1\0\4\56\1\57\53\56\20\0\1\60"+
    "\1\0\2\61\5\0\1\62\3\0\25\62\23\0\1\60"+
    "\1\0\2\23\5\0\1\62\3\0\25\62\32\0\1\63"+
    "\64\0\1\64\64\0\1\65\57\0\2\31\5\0\1\31"+
    "\3\0\25\31\25\0\2\31\5\0\1\31\3\0\15\31"+
    "\1\66\1\31\1\67\5\31\25\0\2\31\5\0\1\31"+
    "\3\0\15\31\1\70\7\31\25\0\2\31\5\0\1\31"+
    "\3\0\12\31\1\71\12\31\25\0\2\31\5\0\1\31"+
    "\3\0\1\72\11\31\1\73\1\31\1\74\1\75\7\31"+
    "\25\0\2\31\5\0\1\31\3\0\5\31\1\76\6\31"+
    "\1\77\10\31\25\0\2\31\5\0\1\31\3\0\1\100"+
    "\3\31\1\101\3\31\1\102\4\31\1\103\7\31\25\0"+
    "\2\31\5\0\1\31\3\0\22\31\1\104\2\31\25\0"+
    "\2\31\5\0\1\31\3\0\17\31\1\105\5\31\25\0"+
    "\2\31\5\0\1\31\3\0\4\31\1\106\20\31\25\0"+
    "\2\31\5\0\1\31\3\0\21\31\1\107\3\31\25\0"+
    "\2\31\5\0\1\31\3\0\17\31\1\110\5\31\25\0"+
    "\2\31\5\0\1\31\3\0\7\31\1\111\15\31\66\0"+
    "\1\112\23\0\2\113\63\0\2\61\5\0\1\62\3\0"+
    "\25\62\25\0\2\62\5\0\1\62\3\0\25\62\25\0"+
    "\2\31\5\0\1\31\3\0\15\31\1\114\7\31\25\0"+
    "\2\31\5\0\1\31\3\0\4\31\1\115\20\31\25\0"+
    "\2\31\5\0\1\31\3\0\14\31\1\116\10\31\25\0"+
    "\2\31\5\0\1\31\3\0\10\31\1\117\7\31\1\120"+
    "\4\31\25\0\2\31\5\0\1\31\3\0\12\31\1\121"+
    "\12\31\25\0\2\31\5\0\1\31\3\0\15\31\1\122"+
    "\7\31\25\0\2\31\5\0\1\31\3\0\17\31\1\123"+
    "\5\31\25\0\2\31\5\0\1\31\3\0\21\31\1\124"+
    "\3\31\25\0\2\31\5\0\1\31\3\0\24\31\1\125"+
    "\25\0\2\31\5\0\1\31\3\0\1\126\2\31\1\127"+
    "\21\31\25\0\2\31\5\0\1\31\3\0\14\31\1\130"+
    "\10\31\25\0\2\31\5\0\1\31\3\0\3\31\1\131"+
    "\21\31\25\0\2\31\5\0\1\31\3\0\12\31\1\132"+
    "\12\31\25\0\2\31\5\0\1\31\3\0\10\31\1\133"+
    "\14\31\25\0\2\31\5\0\1\31\3\0\21\31\1\134"+
    "\3\31\25\0\2\31\5\0\1\31\3\0\17\31\1\135"+
    "\5\31\25\0\2\31\5\0\1\31\3\0\22\31\1\136"+
    "\2\31\25\0\2\31\5\0\1\31\3\0\10\31\1\137"+
    "\14\31\25\0\2\31\5\0\1\31\3\0\12\31\1\140"+
    "\12\31\25\0\2\31\5\0\1\31\3\0\1\141\24\31"+
    "\25\0\2\31\5\0\1\31\3\0\21\31\1\142\3\31"+
    "\25\0\2\31\5\0\1\31\3\0\5\31\1\143\17\31"+
    "\25\0\2\31\5\0\1\31\3\0\4\31\1\144\20\31"+
    "\25\0\2\31\5\0\1\31\3\0\20\31\1\145\4\31"+
    "\25\0\2\31\5\0\1\31\3\0\1\146\24\31\25\0"+
    "\2\31\5\0\1\31\3\0\14\31\1\147\10\31\25\0"+
    "\2\31\5\0\1\31\3\0\10\31\1\150\14\31\25\0"+
    "\2\31\5\0\1\31\3\0\4\31\1\151\20\31\25\0"+
    "\2\31\5\0\1\31\3\0\12\31\1\152\12\31\25\0"+
    "\2\31\5\0\1\31\3\0\14\31\1\153\10\31\25\0"+
    "\2\31\5\0\1\31\3\0\22\31\1\154\2\31\25\0"+
    "\2\31\5\0\1\31\3\0\10\31\1\155\14\31\25\0"+
    "\2\31\5\0\1\31\3\0\4\31\1\156\20\31\25\0"+
    "\2\31\5\0\1\31\3\0\12\31\1\157\12\31\25\0"+
    "\2\31\5\0\1\31\3\0\11\31\1\160\13\31\25\0"+
    "\2\31\5\0\1\31\3\0\10\31\1\161\14\31\25\0"+
    "\2\31\5\0\1\31\3\0\4\31\1\162\20\31\25\0"+
    "\2\31\5\0\1\31\3\0\21\31\1\163\3\31\25\0"+
    "\2\31\5\0\1\31\3\0\1\164\24\31\25\0\2\31"+
    "\5\0\1\31\3\0\21\31\1\165\3\31\25\0\2\31"+
    "\5\0\1\31\3\0\17\31\1\166\5\31\25\0\2\31"+
    "\5\0\1\31\3\0\14\31\1\167\10\31\25\0\2\31"+
    "\5\0\1\31\3\0\4\31\1\170\20\31\25\0\2\31"+
    "\5\0\1\31\3\0\14\31\1\171\10\31\25\0\2\31"+
    "\5\0\1\31\3\0\14\31\1\172\10\31\25\0\2\31"+
    "\5\0\1\31\3\0\14\31\1\173\10\31\25\0\2\31"+
    "\5\0\1\31\3\0\6\31\1\174\16\31\25\0\2\31"+
    "\5\0\1\31\3\0\22\31\1\175\2\31\25\0\2\31"+
    "\5\0\1\31\3\0\4\31\1\176\20\31\3\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[4134];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\3\1\1\11\2\1\10\11\2\1\2\11"+
    "\4\1\3\11\14\1\1\11\1\1\3\11\1\0\1\1"+
    "\1\0\2\1\3\11\24\1\1\11\64\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[126];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
    /*Estos son los lexemas, se implementan en otro orden por eso las listas de aqui abajo
    solo sirven para tener una idea de los lexemas que se pueden encontrar en el código*/
    // String[] palabrasReservadas_RW = {"if", "else", "while", "for", "return", "break", "continue", "fn", "bool", "int", "float", "string", "true", "false", "null"};
    // String[] palabrasReservadas_RW_Extra = {"mean", "max", "min", "median", "mode"};
    // String[] identificadores_ID = {"Nombres de variables", "funciones", "procedimientos", "tipos de datos"};
    // String[] operadoresAritmeticos_OP_AR = {"+", "-", "*", "/", "%"};
    // String[] operadoresRelacionales_OP_REL = {"<", "<=", ">", ">=", "==", "!="};
    // String[] operadoresLogicos_OP_LOG = {"&&", "||", "!"};
    // String[] operadorAsignacion_OP_ASIGN = {"="};
    // String[] delimitadoresParentesis_DEL_LR = {"(", ")", "[", "]", "{", "}"};
    // String[] delimitadoresComillasComentarios_COM = {"\"", "'"};
    // String[] delimitadoresPuntuacion_DEL_PUNT = {";", ",", ".", ":"};
    // String[] literalesNumericos = {"MAX_INT", "MAX_FLOAT"};
    // String[] literalesCadena = {"\"\"", "'C'"};
    // String[] literalesBooleanos_LIT_BOOL = {"true", "false"};
    // String[] comentarios = {"Se utilizan para documentar el código y no son interpretados por el compilador. comienzan con #"};

    // String[] ALL_TOKENS = ['IF', 'ELSE', 'ELIF', 'WHILE', 'FOR', 'RETURN', 'BREAK', 'CONTINUE', 'FN', 'BOOL', 'INT', 'FLOAT', 'STRING', 'TRUE', 'FALSE', 'NULL', 'MEAN', 'MAX', 'MIN', 'MEDIAN', 'MODE', 'OP_SUMA', 'OP_RESTA', 'OP_MULT', 'OP_DIV', 'OP_MOD', 'OP_MENOR', 'OP_MENOR_IGUAL', 'OP_MAYOR', 'OP_MAYOR_IGUAL', 'OP_IGUAL', 'OP_DIFERENTE', 'OP_AND', 'OP_OR', 'OP_NOT', 'OP_ASIGN', 'L_PARENTESIS', 'R_PARENTESIS', 'L_LLAVE', 'R_LLAVE', 'L_CORCHETE', 'R_CORCHETE', 'COMA', 'PUNTO_COMA', 'PUNTO', 'DOS_PUNTOS', 'NUM_ENTERO', 'NUM_FLOTANTE', 'STRING', 'E_NUM_START_ZERO', 'E_ID_NO_', 'E_SIMB_NOT_FOUND']

    /* Explicación: se usa un enum de java que "enumera" cada nombre con un numero, esto se hace porque aun no se puede usar Symbol y Token de java_cup.runtime porque se necesita un archivo CUP y aun no se puede usar la libreria CUP porque hace parte del taller 2 y el profe prohibió eso, asi que en taller 1 --> enum */
    
    private Token token(TokenType type, String lexeme, int line, int column){
        return new Token(type, lexeme, line, column);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public Token yylex() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
              {
                return new Token(TokenType.EOF, "", yyline, yycolumn);
              }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return token(TokenType.E_SIMB_NOT_FOUND, yytext(), yyline, yycolumn);
            }
          // fall through
          case 56: break;
          case 2:
            { /*Ignorar*/
            }
          // fall through
          case 57: break;
          case 3:
            { return token(TokenType.OP_NOT, yytext(), yyline, yycolumn);
            }
          // fall through
          case 58: break;
          case 4:
            { return token(TokenType.OP_MOD, yytext(), yyline, yycolumn);
            }
          // fall through
          case 59: break;
          case 5:
            { return token(TokenType.L_PARENTESIS, yytext(), yyline, yycolumn);
            }
          // fall through
          case 60: break;
          case 6:
            { return token(TokenType.R_PARENTESIS, yytext(), yyline, yycolumn);
            }
          // fall through
          case 61: break;
          case 7:
            { return token(TokenType.OP_MULT, yytext(), yyline, yycolumn);
            }
          // fall through
          case 62: break;
          case 8:
            { return token(TokenType.OP_SUMA, yytext(), yyline, yycolumn);
            }
          // fall through
          case 63: break;
          case 9:
            { return token(TokenType.COMA, yytext(), yyline, yycolumn);
            }
          // fall through
          case 64: break;
          case 10:
            { return token(TokenType.OP_RESTA, yytext(), yyline, yycolumn);
            }
          // fall through
          case 65: break;
          case 11:
            { return token(TokenType.PUNTO, yytext(), yyline, yycolumn);
            }
          // fall through
          case 66: break;
          case 12:
            { return token(TokenType.OP_DIV, yytext(), yyline, yycolumn);
            }
          // fall through
          case 67: break;
          case 13:
            { return token(TokenType.NUM_ENTERO, yytext(), yyline, yycolumn);
            }
          // fall through
          case 68: break;
          case 14:
            { return token(TokenType.DOS_PUNTOS, yytext(), yyline, yycolumn);
            }
          // fall through
          case 69: break;
          case 15:
            { return token(TokenType.PUNTO_COMA, yytext(), yyline, yycolumn);
            }
          // fall through
          case 70: break;
          case 16:
            { return token(TokenType.OP_MENOR, yytext(), yyline, yycolumn);
            }
          // fall through
          case 71: break;
          case 17:
            { return token(TokenType.OP_ASIGN, yytext(), yyline, yycolumn);
            }
          // fall through
          case 72: break;
          case 18:
            { return token(TokenType.OP_MAYOR, yytext(), yyline, yycolumn);
            }
          // fall through
          case 73: break;
          case 19:
            { return token(TokenType.IDENTIFICADOR, yytext(), yyline, yycolumn);
            }
          // fall through
          case 74: break;
          case 20:
            { return token(TokenType.L_CORCHETE, yytext(), yyline, yycolumn);
            }
          // fall through
          case 75: break;
          case 21:
            { return token(TokenType.R_CORCHETE, yytext(), yyline, yycolumn);
            }
          // fall through
          case 76: break;
          case 22:
            { return token(TokenType.OP_POT, yytext(), yyline, yycolumn);
            }
          // fall through
          case 77: break;
          case 23:
            { return token(TokenType.L_LLAVE, yytext(), yyline, yycolumn);
            }
          // fall through
          case 78: break;
          case 24:
            { return token(TokenType.R_LLAVE, yytext(), yyline, yycolumn);
            }
          // fall through
          case 79: break;
          case 25:
            { return token(TokenType.OP_DIFERENTE, yytext(), yyline, yycolumn);
            }
          // fall through
          case 80: break;
          case 26:
            { return token(TokenType.OP_AND, yytext(), yyline, yycolumn);
            }
          // fall through
          case 81: break;
          case 27:
            { return token(TokenType.STRING, yytext(), yyline, yycolumn);
            }
          // fall through
          case 82: break;
          case 28:
            { return token(TokenType.E_NUM_START_ZERO, yytext(), yyline, yycolumn);
            }
          // fall through
          case 83: break;
          case 29:
            { return token(TokenType.E_ID_START_DIGIT, yytext(), yyline, yycolumn);
            }
          // fall through
          case 84: break;
          case 30:
            { return token(TokenType.OP_MENOR_IGUAL, yytext(), yyline, yycolumn);
            }
          // fall through
          case 85: break;
          case 31:
            { return token(TokenType.OP_IGUAL, yytext(), yyline, yycolumn);
            }
          // fall through
          case 86: break;
          case 32:
            { return token(TokenType.OP_MAYOR_IGUAL, yytext(), yyline, yycolumn);
            }
          // fall through
          case 87: break;
          case 33:
            { return token(TokenType.FN, yytext(), yyline, yycolumn);
            }
          // fall through
          case 88: break;
          case 34:
            { return token(TokenType.IF, yytext(), yyline, yycolumn);
            }
          // fall through
          case 89: break;
          case 35:
            { return token(TokenType.OP_OR, yytext(), yyline, yycolumn);
            }
          // fall through
          case 90: break;
          case 36:
            { return token(TokenType.NUM_FLOTANTE, yytext(), yyline, yycolumn);
            }
          // fall through
          case 91: break;
          case 37:
            { return token(TokenType.FOR, yytext(), yyline, yycolumn);
            }
          // fall through
          case 92: break;
          case 38:
            { return token(TokenType.INT, yytext(), yyline, yycolumn);
            }
          // fall through
          case 93: break;
          case 39:
            { return token(TokenType.MAX, yytext(), yyline, yycolumn);
            }
          // fall through
          case 94: break;
          case 40:
            { return token(TokenType.MIN, yytext(), yyline, yycolumn);
            }
          // fall through
          case 95: break;
          case 41:
            { return token(TokenType.BOOL, yytext(), yyline, yycolumn);
            }
          // fall through
          case 96: break;
          case 42:
            { return token(TokenType.ELIF, yytext(), yyline, yycolumn);
            }
          // fall through
          case 97: break;
          case 43:
            { return token(TokenType.ELSE, yytext(), yyline, yycolumn);
            }
          // fall through
          case 98: break;
          case 44:
            { return token(TokenType.MEAN, yytext(), yyline, yycolumn);
            }
          // fall through
          case 99: break;
          case 45:
            { return token(TokenType.MODE, yytext(), yyline, yycolumn);
            }
          // fall through
          case 100: break;
          case 46:
            { return token(TokenType.NULL, yytext(), yyline, yycolumn);
            }
          // fall through
          case 101: break;
          case 47:
            { return token(TokenType.TRUE, yytext(), yyline, yycolumn);
            }
          // fall through
          case 102: break;
          case 48:
            { return token(TokenType.BREAK, yytext(), yyline, yycolumn);
            }
          // fall through
          case 103: break;
          case 49:
            { return token(TokenType.FALSE, yytext(), yyline, yycolumn);
            }
          // fall through
          case 104: break;
          case 50:
            { return token(TokenType.FLOAT, yytext(), yyline, yycolumn);
            }
          // fall through
          case 105: break;
          case 51:
            { return token(TokenType.PRINT, yytext(), yyline, yycolumn);
            }
          // fall through
          case 106: break;
          case 52:
            { return token(TokenType.WHILE, yytext(), yyline, yycolumn);
            }
          // fall through
          case 107: break;
          case 53:
            { return token(TokenType.MEDIAN, yytext(), yyline, yycolumn);
            }
          // fall through
          case 108: break;
          case 54:
            { return token(TokenType.RETURN, yytext(), yyline, yycolumn);
            }
          // fall through
          case 109: break;
          case 55:
            { return token(TokenType.CONTINUE, yytext(), yyline, yycolumn);
            }
          // fall through
          case 110: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
