// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/Data/Lexer.flex

package model.scanner;
import java.util.List;
import java.util.ArrayList;

import java_cup.runtime.*;

import model.scanner.Token.*;


@SuppressWarnings("fallthrough")
public class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
          0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
          "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
          "\11\0\1\1\1\2\1\3\1\4\1\5\22\0\1\1"+
                  "\1\6\1\7\1\10\1\0\1\11\1\12\1\13\1\14"+
                  "\1\15\1\16\1\17\1\20\1\21\1\22\1\23\1\24"+
                  "\11\25\1\26\1\27\1\30\1\31\1\32\2\0\1\33"+
                  "\1\34\1\35\2\34\1\36\24\34\1\37\1\40\1\41"+
                  "\1\42\1\34\1\0\1\43\1\44\1\45\1\46\1\47"+
                  "\1\50\1\51\1\52\1\53\1\34\1\54\1\55\1\56"+
                  "\1\57\1\60\1\61\1\34\1\62\1\63\1\64\1\65"+
                  "\1\34\1\66\1\67\1\70\1\34\1\71\1\72\1\73"+
                  "\7\0\1\3\73\0\1\34\7\0\1\34\3\0\1\34"+
                  "\3\0\1\34\1\0\1\34\6\0\1\34\1\0\1\34"+
                  "\4\0\1\34\7\0\1\34\3\0\1\34\3\0\1\34"+
                  "\1\0\1\34\6\0\1\34\1\0\1\34\u012b\0\2\3"+
                  "\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
          "\1\0\1\1\2\2\1\3\1\1\1\2\1\4\2\1"+
                  "\1\5\1\6\1\7\1\10\1\11\1\12\1\13\1\14"+
                  "\2\15\1\16\1\17\1\20\1\21\1\22\1\23\1\24"+
                  "\1\1\1\25\1\26\16\23\1\27\1\1\1\30\1\31"+
                  "\1\0\1\32\1\0\1\33\2\0\1\2\1\0\1\34"+
                  "\1\35\1\36\1\37\1\40\2\0\6\23\1\41\2\23"+
                  "\1\42\15\23\1\43\1\44\2\0\10\23\1\45\1\23"+
                  "\1\46\1\47\1\50\2\23\1\51\10\23\2\0\3\23"+
                  "\1\52\1\53\1\54\4\23\1\55\1\23\1\56\1\57"+
                  "\2\23\1\60\1\23\1\61\1\23\2\0\1\23\1\62"+
                  "\1\23\1\63\1\64\3\23\1\65\2\23\1\66\2\0"+
                  "\4\23\1\67\1\23\1\70\1\71\2\0\1\72\2\23"+
                  "\1\73\1\74\2\0\1\75\1\76\1\23\2\0\1\23"+
                  "\2\0\1\23\2\0\1\23\2\0\1\23\2\0\1\23"+
                  "\2\0\1\23\2\0\1\23\2\0\1\77\16\0";

  private static int [] zzUnpackAction() {
    int [] result = new int[210];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
          "\0\0\0\74\0\74\0\170\0\264\0\360\0\u012c\0\74"+
                  "\0\u0168\0\u01a4\0\74\0\74\0\74\0\74\0\74\0\74"+
                  "\0\74\0\u01e0\0\u021c\0\u0258\0\74\0\74\0\u0294\0\u02d0"+
                  "\0\u030c\0\u0348\0\74\0\u0384\0\74\0\74\0\u03c0\0\u03fc"+
                  "\0\u0438\0\u0474\0\u04b0\0\u04ec\0\u0528\0\u0564\0\u05a0\0\u05dc"+
                  "\0\u0618\0\u0654\0\u0690\0\u06cc\0\74\0\u0708\0\74\0\74"+
                  "\0\360\0\74\0\u0744\0\74\0\u01a4\0\u0780\0\u07bc\0\u07f8"+
                  "\0\u0834\0\u0870\0\74\0\74\0\74\0\u08ac\0\u08e8\0\u0924"+
                  "\0\u0960\0\u099c\0\u09d8\0\u0a14\0\u0a50\0\u0348\0\u0a8c\0\u0ac8"+
                  "\0\u0348\0\u0b04\0\u0b40\0\u0b7c\0\u0bb8\0\u0bf4\0\u0c30\0\u0c6c"+
                  "\0\u0ca8\0\u0ce4\0\u0d20\0\u0d5c\0\u0d98\0\u0dd4\0\74\0\u07f8"+
                  "\0\u0e10\0\u0e4c\0\u0e88\0\u0ec4\0\u0f00\0\u0f3c\0\u0f78\0\u0fb4"+
                  "\0\u0ff0\0\u102c\0\u0348\0\u1068\0\u0348\0\u0348\0\u0348\0\u10a4"+
                  "\0\u10e0\0\u0348\0\u111c\0\u1158\0\u1194\0\u11d0\0\u120c\0\u1248"+
                  "\0\u1284\0\u12c0\0\u12fc\0\u1338\0\u1374\0\u13b0\0\u13ec\0\u0348"+
                  "\0\u0348\0\u0348\0\u1428\0\u1464\0\u14a0\0\u14dc\0\u0348\0\u1518"+
                  "\0\u0348\0\u0348\0\u1554\0\u1590\0\u0348\0\u15cc\0\u0348\0\u1608"+
                  "\0\u1644\0\u1680\0\u16bc\0\u0348\0\u16f8\0\u0348\0\u0348\0\u1734"+
                  "\0\u1770\0\u17ac\0\u17e8\0\u1824\0\u1860\0\u0348\0\u189c\0\u18d8"+
                  "\0\u1914\0\u1950\0\u198c\0\u19c8\0\u0348\0\u1a04\0\u0348\0\u0348"+
                  "\0\u1a40\0\u1a7c\0\u0348\0\u1ab8\0\u1af4\0\u1b30\0\u0348\0\u1b6c"+
                  "\0\u1ba8\0\u0348\0\u0348\0\u1be4\0\u1c20\0\u1c5c\0\u1c98\0\u1cd4"+
                  "\0\u1d10\0\u1d4c\0\u1d88\0\u1dc4\0\u1e00\0\u1e3c\0\u1e78\0\u1eb4"+
                  "\0\u1ef0\0\u1f2c\0\u1f68\0\u1fa4\0\u1fe0\0\u201c\0\u2058\0\u2094"+
                  "\0\u20d0\0\u210c\0\u2148\0\u0348\0\u2184\0\u21c0\0\u21fc\0\u2238"+
                  "\0\u2274\0\u22b0\0\u22ec\0\u2328\0\u2364\0\u23a0\0\u23dc\0\u2418"+
                  "\0\u2454\0\u2490";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[210];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
          "\1\2\2\3\1\0\1\3\1\4\1\5\1\6\1\7"+
                  "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
                  "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\1\27"+
                  "\1\30\1\31\4\32\1\33\1\34\1\35\1\36\1\32"+
                  "\1\37\1\40\1\32\1\41\1\42\1\43\1\32\1\44"+
                  "\1\32\1\45\1\46\1\47\1\32\1\50\1\51\1\52"+
                  "\1\53\1\32\1\54\2\32\1\55\1\56\1\57\76\0"+
                  "\1\3\122\0\1\60\42\0\7\61\1\62\30\61\1\63"+
                  "\33\61\2\7\1\3\2\7\1\4\66\7\12\0\1\64"+
                  "\61\0\13\65\1\62\24\65\1\66\33\65\23\0\1\67"+
                  "\72\0\1\70\1\0\2\71\5\0\4\72\4\0\26\72"+
                  "\25\0\1\70\1\0\2\24\5\0\4\72\4\0\26\72"+
                  "\34\0\1\73\73\0\1\74\73\0\1\75\66\0\2\32"+
                  "\5\0\4\32\4\0\26\32\12\0\1\76\3\0\1\77"+
                  "\104\0\2\32\5\0\4\32\4\0\15\32\1\100\1\32"+
                  "\1\101\6\32\27\0\2\32\5\0\4\32\4\0\15\32"+
                  "\1\102\10\32\27\0\2\32\5\0\4\32\4\0\12\32"+
                  "\1\103\13\32\27\0\2\32\5\0\4\32\4\0\1\104"+
                  "\11\32\1\105\1\32\1\106\1\107\10\32\27\0\2\32"+
                  "\5\0\4\32\4\0\4\32\1\110\21\32\27\0\2\32"+
                  "\5\0\4\32\4\0\5\32\1\111\6\32\1\112\11\32"+
                  "\27\0\2\32\5\0\4\32\4\0\4\32\1\113\21\32"+
                  "\27\0\2\32\5\0\4\32\4\0\1\114\3\32\1\115"+
                  "\3\32\1\116\4\32\1\117\10\32\27\0\2\32\5\0"+
                  "\4\32\4\0\22\32\1\120\3\32\27\0\2\32\5\0"+
                  "\4\32\4\0\17\32\1\121\6\32\27\0\2\32\5\0"+
                  "\4\32\4\0\4\32\1\122\21\32\27\0\2\32\5\0"+
                  "\4\32\4\0\15\32\1\123\3\32\1\124\4\32\27\0"+
                  "\2\32\5\0\4\32\4\0\17\32\1\125\6\32\27\0"+
                  "\2\32\5\0\4\32\4\0\7\32\1\126\16\32\75\0"+
                  "\1\127\1\0\2\61\4\0\66\61\2\65\4\0\66\65"+
                  "\2\67\1\0\71\67\24\0\2\130\72\0\2\71\5\0"+
                  "\4\72\4\0\26\72\27\0\2\72\5\0\4\72\4\0"+
                  "\26\72\43\0\1\131\73\0\1\132\57\0\2\32\5\0"+
                  "\4\32\4\0\15\32\1\133\10\32\27\0\2\32\5\0"+
                  "\4\32\4\0\4\32\1\134\21\32\27\0\2\32\5\0"+
                  "\4\32\4\0\14\32\1\135\1\32\1\136\7\32\27\0"+
                  "\2\32\5\0\4\32\4\0\10\32\1\137\7\32\1\140"+
                  "\5\32\27\0\2\32\5\0\4\32\4\0\12\32\1\141"+
                  "\13\32\27\0\2\32\5\0\4\32\4\0\15\32\1\142"+
                  "\10\32\27\0\2\32\5\0\4\32\4\0\17\32\1\143"+
                  "\6\32\27\0\2\32\5\0\4\32\4\0\21\32\1\144"+
                  "\4\32\27\0\2\32\5\0\4\32\4\0\21\32\1\145"+
                  "\4\32\27\0\2\32\5\0\4\32\4\0\14\32\1\146"+
                  "\11\32\27\0\2\32\5\0\4\32\4\0\24\32\1\147"+
                  "\1\32\27\0\2\32\5\0\4\32\4\0\1\150\2\32"+
                  "\1\151\22\32\27\0\2\32\5\0\4\32\4\0\14\32"+
                  "\1\152\11\32\27\0\2\32\5\0\4\32\4\0\3\32"+
                  "\1\153\22\32\27\0\2\32\5\0\4\32\4\0\12\32"+
                  "\1\154\13\32\27\0\2\32\5\0\4\32\4\0\10\32"+
                  "\1\155\15\32\27\0\2\32\5\0\4\32\4\0\21\32"+
                  "\1\156\4\32\27\0\2\32\5\0\4\32\4\0\17\32"+
                  "\1\157\6\32\27\0\2\32\5\0\4\32\4\0\17\32"+
                  "\1\160\6\32\27\0\2\32\5\0\4\32\4\0\22\32"+
                  "\1\161\3\32\27\0\2\32\5\0\4\32\4\0\10\32"+
                  "\1\162\15\32\12\0\1\163\77\0\1\164\104\0\2\32"+
                  "\5\0\4\32\4\0\12\32\1\165\13\32\27\0\2\32"+
                  "\5\0\4\32\4\0\1\166\25\32\27\0\2\32\5\0"+
                  "\4\32\4\0\21\32\1\167\4\32\27\0\2\32\5\0"+
                  "\4\32\4\0\25\32\1\170\27\0\2\32\5\0\4\32"+
                  "\4\0\5\32\1\171\20\32\27\0\2\32\5\0\4\32"+
                  "\4\0\4\32\1\172\21\32\27\0\2\32\5\0\4\32"+
                  "\4\0\20\32\1\173\5\32\27\0\2\32\5\0\4\32"+
                  "\4\0\1\174\25\32\27\0\2\32\5\0\1\175\1\32"+
                  "\1\176\1\32\4\0\26\32\27\0\2\32\5\0\4\32"+
                  "\4\0\14\32\1\177\11\32\27\0\2\32\5\0\4\32"+
                  "\4\0\10\32\1\200\15\32\27\0\2\32\5\0\4\32"+
                  "\4\0\4\32\1\201\21\32\27\0\2\32\5\0\4\32"+
                  "\4\0\12\32\1\202\13\32\27\0\2\32\5\0\4\32"+
                  "\4\0\14\32\1\203\11\32\27\0\2\32\5\0\4\32"+
                  "\4\0\22\32\1\204\3\32\27\0\2\32\5\0\4\32"+
                  "\4\0\21\32\1\205\4\32\27\0\2\32\5\0\4\32"+
                  "\4\0\10\32\1\206\15\32\27\0\2\32\5\0\4\32"+
                  "\4\0\4\32\1\207\21\32\27\0\2\32\5\0\4\32"+
                  "\4\0\12\32\1\210\13\32\43\0\1\211\73\0\1\212"+
                  "\57\0\2\32\5\0\4\32\4\0\4\32\1\213\21\32"+
                  "\27\0\2\32\5\0\4\32\4\0\11\32\1\214\14\32"+
                  "\27\0\2\32\5\0\4\32\4\0\10\32\1\215\15\32"+
                  "\27\0\2\32\5\0\4\32\4\0\4\32\1\216\21\32"+
                  "\27\0\2\32\5\0\4\32\4\0\21\32\1\217\4\32"+
                  "\27\0\2\32\5\0\4\32\4\0\20\32\1\220\5\32"+
                  "\27\0\2\32\5\0\4\32\4\0\7\32\1\221\16\32"+
                  "\27\0\2\32\5\0\4\32\4\0\1\222\25\32\27\0"+
                  "\2\32\5\0\4\32\4\0\21\32\1\223\4\32\27\0"+
                  "\2\32\5\0\4\32\4\0\17\32\1\224\6\32\27\0"+
                  "\2\32\5\0\4\32\4\0\14\32\1\225\11\32\27\0"+
                  "\2\32\5\0\4\32\4\0\4\32\1\226\21\32\12\0"+
                  "\1\227\77\0\1\230\104\0\2\32\5\0\4\32\4\0"+
                  "\1\231\25\32\27\0\2\32\5\0\4\32\4\0\14\32"+
                  "\1\232\11\32\27\0\2\32\5\0\4\32\4\0\2\32"+
                  "\1\233\23\32\27\0\2\32\5\0\4\32\4\0\1\234"+
                  "\25\32\27\0\2\32\5\0\4\32\4\0\14\32\1\235"+
                  "\11\32\27\0\2\32\5\0\4\32\4\0\12\32\1\236"+
                  "\13\32\27\0\2\32\5\0\4\32\4\0\14\32\1\237"+
                  "\11\32\27\0\2\32\5\0\4\32\4\0\6\32\1\240"+
                  "\17\32\17\0\1\241\73\0\1\242\103\0\2\32\5\0"+
                  "\4\32\4\0\14\32\1\243\11\32\27\0\2\32\5\0"+
                  "\4\32\4\0\22\32\1\244\3\32\27\0\2\32\5\0"+
                  "\4\32\4\0\10\32\1\245\15\32\27\0\2\32\5\0"+
                  "\4\32\4\0\17\32\1\246\6\32\27\0\2\32\5\0"+
                  "\4\32\4\0\14\32\1\247\11\32\43\0\1\250\73\0"+
                  "\1\251\57\0\2\32\5\0\4\32\4\0\4\32\1\252"+
                  "\21\32\27\0\2\32\5\0\4\32\4\0\10\32\1\253"+
                  "\15\32\27\0\2\32\5\0\3\32\1\254\4\0\26\32"+
                  "\43\0\1\255\73\0\1\256\57\0\2\32\5\0\4\32"+
                  "\4\0\17\32\1\257\6\32\25\0\1\260\73\0\1\261"+
                  "\75\0\2\32\5\0\4\32\4\0\15\32\1\262\10\32"+
                  "\75\0\1\263\73\0\1\264\25\0\2\32\5\0\4\32"+
                  "\4\0\13\32\1\265\12\32\42\0\1\266\73\0\1\267"+
                  "\60\0\2\32\5\0\1\270\3\32\4\0\26\32\45\0"+
                  "\1\271\73\0\1\272\55\0\2\32\5\0\4\32\4\0"+
                  "\20\32\1\273\5\32\43\0\1\274\73\0\1\275\57\0"+
                  "\2\32\5\0\4\32\4\0\2\32\1\276\23\32\43\0"+
                  "\1\277\73\0\1\300\57\0\2\32\5\0\4\32\4\0"+
                  "\10\32\1\301\15\32\44\0\1\302\73\0\1\303\56\0"+
                  "\2\32\5\0\4\32\4\0\10\32\1\304\15\32\20\0"+
                  "\1\305\73\0\1\306\74\0\1\307\73\0\1\310\115\0"+
                  "\1\311\73\0\1\312\42\0\1\313\77\0\1\314\120\0"+
                  "\1\315\73\0\1\316\42\0\1\317\77\0\1\320\120\0"+
                  "\1\321\73\0\1\322\42\0\1\3\77\0\1\3\60\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[9420];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
          "Unknown internal scanner error",
          "Error: could not match input",
          "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
          "\1\0\2\11\4\1\1\11\2\1\7\11\3\1\2\11"+
                  "\4\1\1\11\1\1\2\11\16\1\1\11\1\1\2\11"+
                  "\1\0\1\11\1\0\1\11\2\0\1\1\1\0\2\1"+
                  "\3\11\2\0\27\1\1\11\1\1\2\0\30\1\2\0"+
                  "\24\1\2\0\14\1\2\0\10\1\2\0\5\1\2\0"+
                  "\3\1\2\0\1\1\2\0\1\1\2\0\1\1\2\0"+
                  "\1\1\2\0\1\1\2\0\1\1\2\0\1\1\2\0"+
                  "\1\1\16\0";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[210];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
  StringBuffer string = new StringBuffer();
  List<Token> tokens = new ArrayList<>();
  List<Token> errors = new ArrayList<>();
  List<String> errorsMessages = new ArrayList<>();

  public  List<Token> getTokens(){return tokens;}

  public  List<Token> getErrors(){return errors;}

  public  List<String> getErrorsMessages(){return errorsMessages;}

  private boolean isToken(Object type){
    return type instanceof TokenType;
  }
  private Symbol symbol(Object type){
    return symbol(type, "");
  }
  private Symbol symbol(Object type, Object value){
    int n = (isToken(type)) ? ((TokenType)type).ordinal() : (int) type;
    Token token = new Token(TokenType.getType(n), value.toString(), yyline, yycolumn);
    tokens.add(token);
    if (n == 1) errors.add(token);
    return new Symbol(n, value);
  }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
              zzBuffer, 0,
              zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
                "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzCurrentPos = 0;
    zzMarkedPos = 0;
    zzStartRead = 0;
    zzEndRead = 0;
    zzFinalHighSurrogate = 0;
    yyline = 0;
    yycolumn = 0;
    yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;

      yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
          case '\u000B':  // fall through
          case '\u000C':  // fall through
          case '\u0085':  // fall through
          case '\u2028':  // fall through
          case '\u2029':
            yyline++;
            yycolumn = 0;
            zzR = false;
            break;
          case '\r':
            yyline++;
            yycolumn = 0;
            zzR = true;
            break;
          case '\n':
            if (zzR)
              zzR = false;
            else {
              yyline++;
              yycolumn = 0;
            }
            break;
          default:
            zzR = false;
            yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        zzDoEOF();
        { return symbol(TokenType.EOF);
        }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
          { String error = "Error léxico en la línea " + yyline + ", columna " + yycolumn + ": Carácter inesperado: " + yytext();
            this.errorsMessages.add(error);
            return symbol(TokenType.ERROR, yytext());
          }
          // fall through
          case 64: break;
          case 2:
          { /*Ignorar*/
          }
          // fall through
          case 65: break;
          case 3:
          { return symbol(TokenType.OP_NOT, yytext());
          }
          // fall through
          case 66: break;
          case 4:
          { return symbol(TokenType.OP_MOD, yytext());
          }
          // fall through
          case 67: break;
          case 5:
          { return symbol(TokenType.L_PARENTESIS, yytext());
          }
          // fall through
          case 68: break;
          case 6:
          { return symbol(TokenType.R_PARENTESIS, yytext());
          }
          // fall through
          case 69: break;
          case 7:
          { return symbol(TokenType.OP_MULT, yytext());
          }
          // fall through
          case 70: break;
          case 8:
          { return symbol(TokenType.OP_SUMA, yytext());
          }
          // fall through
          case 71: break;
          case 9:
          { return symbol(TokenType.COMA, yytext());
          }
          // fall through
          case 72: break;
          case 10:
          { return symbol(TokenType.OP_RESTA, yytext());
          }
          // fall through
          case 73: break;
          case 11:
          { return symbol(TokenType.PUNTO, yytext());
          }
          // fall through
          case 74: break;
          case 12:
          { return symbol(TokenType.OP_DIV, yytext());
          }
          // fall through
          case 75: break;
          case 13:
          { return symbol(TokenType.LIT_INT, Integer.valueOf(yytext()));
          }
          // fall through
          case 76: break;
          case 14:
          { return symbol(TokenType.DOS_PUNTOS, yytext());
          }
          // fall through
          case 77: break;
          case 15:
          { return symbol(TokenType.PUNTO_COMA, yytext());
          }
          // fall through
          case 78: break;
          case 16:
          { return symbol(TokenType.OP_MENOR, yytext());
          }
          // fall through
          case 79: break;
          case 17:
          { return symbol(TokenType.OP_ASIGN, yytext());
          }
          // fall through
          case 80: break;
          case 18:
          { return symbol(TokenType.OP_MAYOR, yytext());
          }
          // fall through
          case 81: break;
          case 19:
          { return symbol(TokenType.IDENTIFICADOR, yytext());
          }
          // fall through
          case 82: break;
          case 20:
          { return symbol(TokenType.L_CORCHETE, yytext());
          }
          // fall through
          case 83: break;
          case 21:
          { return symbol(TokenType.R_CORCHETE, yytext());
          }
          // fall through
          case 84: break;
          case 22:
          { return symbol(TokenType.OP_POT, yytext());
          }
          // fall through
          case 85: break;
          case 23:
          { return symbol(TokenType.L_LLAVE, yytext());
          }
          // fall through
          case 86: break;
          case 24:
          { return symbol(TokenType.R_LLAVE, yytext());
          }
          // fall through
          case 87: break;
          case 25:
          { return symbol(TokenType.OP_DIFERENTE, yytext());
          }
          // fall through
          case 88: break;
          case 26:
          { return symbol(TokenType.LIT_STRING, yytext());
          }
          // fall through
          case 89: break;
          case 27:
          { return symbol(TokenType.OP_AND, yytext());
          }
          // fall through
          case 90: break;
          case 28:
          { String error = "Error léxico en la línea " + yyline + ", columna " + yycolumn + ": los números no deben empezar por 0 (cero): " + yytext();
            this.errorsMessages.add(error);
            return symbol(TokenType.ERROR, yytext());
          }
          // fall through
          case 91: break;
          case 29:
          { String error = "Error léxico en la línea " + yyline + ", columna " + yycolumn + ": Los identificadores (nombres de variables y funciones) no deben empezar por números: " + yytext();
            this.errorsMessages.add(error);
            return symbol(TokenType.ERROR, yytext());
          }
          // fall through
          case 92: break;
          case 30:
          { return symbol(TokenType.OP_MENOR_IGUAL, yytext());
          }
          // fall through
          case 93: break;
          case 31:
          { return symbol(TokenType.OP_IGUAL, yytext());
          }
          // fall through
          case 94: break;
          case 32:
          { return symbol(TokenType.OP_MAYOR_IGUAL, yytext());
          }
          // fall through
          case 95: break;
          case 33:
          { return symbol(TokenType.FN, yytext());
          }
          // fall through
          case 96: break;
          case 34:
          { return symbol(TokenType.IF, yytext());
          }
          // fall through
          case 97: break;
          case 35:
          { return symbol(TokenType.OP_OR, yytext());
          }
          // fall through
          case 98: break;
          case 36:
          { return symbol(TokenType.LIT_FLOAT, Float.valueOf( yytext()) );
          }
          // fall through
          case 99: break;
          case 37:
          { return symbol(TokenType.FOR, yytext());
          }
          // fall through
          case 100: break;
          case 38:
          { return symbol(TokenType.INT, yytext());
          }
          // fall through
          case 101: break;
          case 39:
          { return symbol(TokenType.LEN, yytext());
          }
          // fall through
          case 102: break;
          case 40:
          { return symbol(TokenType.MAX, yytext());
          }
          // fall through
          case 103: break;
          case 41:
          { return symbol(TokenType.MIN, yytext());
          }
          // fall through
          case 104: break;
          case 42:
          { return symbol(TokenType.COPY, yytext());
          }
          // fall through
          case 105: break;
          case 43:
          { return symbol(TokenType.ELIF, yytext());
          }
          // fall through
          case 106: break;
          case 44:
          { return symbol(TokenType.ELSE, yytext());
          }
          // fall through
          case 107: break;
          case 45:
          { return symbol(TokenType.MEAN, yytext());
          }
          // fall through
          case 108: break;
          case 46:
          { return symbol(TokenType.MODE, yytext());
          }
          // fall through
          case 109: break;
          case 47:
          { return symbol(TokenType.NULL, yytext());
          }
          // fall through
          case 110: break;
          case 48:
          { return symbol(TokenType.SORT, yytext());
          }
          // fall through
          case 111: break;
          case 49:
          { return symbol(TokenType.TRUE, yytext());
          }
          // fall through
          case 112: break;
          case 50:
          { return symbol(TokenType.BREAK, yytext());
          }
          // fall through
          case 113: break;
          case 51:
          { return symbol(TokenType.FALSE, yytext());
          }
          // fall through
          case 114: break;
          case 52:
          { return symbol(TokenType.FLOAT, yytext());
          }
          // fall through
          case 115: break;
          case 53:
          { return symbol(TokenType.PRINT, yytext());
          }
          // fall through
          case 116: break;
          case 54:
          { return symbol(TokenType.WHILE, yytext());
          }
          // fall through
          case 117: break;
          case 55:
          { return symbol(TokenType.MEDIAN, yytext());
          }
          // fall through
          case 118: break;
          case 56:
          { return symbol(TokenType.RETURN, yytext());
          }
          // fall through
          case 119: break;
          case 57:
          { return symbol(TokenType.STRING, yytext());
          }
          // fall through
          case 120: break;
          case 58:
          { return symbol(TokenType.BOOLEAN, yytext());
          }
          // fall through
          case 121: break;
          case 59:
          { return symbol(TokenType.GETCHAR, yytext());
          }
          // fall through
          case 122: break;
          case 60:
          { return symbol(TokenType.PRINTLN, yytext());
          }
          // fall through
          case 123: break;
          case 61:
          { return symbol(TokenType.CONTINUE, yytext());
          }
          // fall through
          case 124: break;
          case 62:
          { return symbol(TokenType.GETASCII, yytext());
          }
          // fall through
          case 125: break;
          case 63:
          { return symbol(TokenType.GETCHARFROMASCII, yytext());
          }
          // fall through
          case 126: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
