/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Enum.java to edit this template
 */
package model.scanner;

/**
 *
 * @author Cesar_R
 */
public enum TokenType {
    IF,
    ELSE,
    ELIF,
    WHILE,
    FOR,
    RETURN,
    BREAK,
    CONTINUE,
    FN,
    BOOL,
    INT,
    FLOAT,
    STRING,
    TRUE,
    FALSE,
    NULL,
    PRINT,
    MEAN,
    MAX,
    MIN,
    MEDIAN,
    MODE,
    IDENTIFICADOR,
    OP_SUMA,
    OP_RESTA,
    OP_MULT,
    OP_DIV,
    OP_MOD,
    OP_MENOR,
    OP_MENOR_IGUAL,
    OP_MAYOR,
    OP_MAYOR_IGUAL,
    OP_IGUAL,
    OP_DIFERENTE,
    OP_AND,
    OP_OR,
    OP_NOT,
    OP_ASIGN,
    L_PARENTESIS,
    R_PARENTESIS,
    L_LLAVE,
    R_LLAVE,
    L_CORCHETE,
    R_CORCHETE,
    COMA,
    PUNTO_COMA,
    PUNTO,
    DOS_PUNTOS,
    NUM_ENTERO,
    NUM_FLOTANTE,
    E_NUM_START_ZERO,
    E_SIMB_NOT_FOUND,
    //COMENTARIO_DOC,
    EOF,
}
